version: '2.1'
services:
  mysql:
    image: mysql:5.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: "mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e \"SHOW DATABASES;\""
      interval: 5s
      timeout: 6s
      retries: 10
    # publish mysql server ports to access
    # from outside of container with: mysql -h localhost -P 3306 --protocol=tcp -u directus -p
    # ports:
    #  - "8806:3306"
    # If you need to specify a persistent volume for mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    networks:
      - backend
  directus:
    depends_on:
      mysql:
        condition: service_healthy
    image: getdirectus/directus:6.4
    # links:
    #  - mysql:mysql
    ports:
     - "8080:8080"
    restart: always
    volumes:
    # Switch between named storage, path storage
      - storage:/var/www/html/storage
      # - ./.data/storage:/var/www/html/storage
    # Replace ~/Development/directus with your local directus git checkout
    #    - ~/Development/directus:/var/www/html
    environment:
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_ENV_MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_PORT_3306_TCP_ADDR=mysql
     - MYSQL_PORT_3306_TCP_PORT=3306
     - MYSQL_ENV_MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_ENV_MYSQL_USER=${MYSQL_USER}
    # If you use docker for dev or want to test without opcache - disable with env var
    #  - PHP_OPCACHE_ENABLED=false
    networks: 
      - backend
      - frontend

  frontend:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - directus
    restart: always
    networks: 
      - frontend
volumes:
  storage:
    # If you want to define externally, uncomment and adjust as needed
    # external:
    #   name: directus-storage

networks: 
  frontend:
  backend: